import java.util.Arrays;
import java.util.List;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */

public class App {
    private ItemRepository itemRepository;
    private SalesPromotionRepository salesPromotionRepository;

    public App(ItemRepository itemRepository, SalesPromotionRepository salesPromotionRepository) {
        this.itemRepository = itemRepository;
        this.salesPromotionRepository = salesPromotionRepository;
    }

    public String bestCharge(List<String> inputs) {
        //TODO: write code here
        List<Item> items = this.itemRepository.findAll();
        List<SalesPromotion> allsales = this.salesPromotionRepository.findAll();
        Boolean isHalf = false;
        double tempTotal = 0;
        double halfTotal = 0;
        String outContent = "============= Order details =============\n";
        String halfItems = " (";
        for(int i=0;i<inputs.size();i++){
            String InputOne = inputs.get(i);
            String SplitData[] = InputOne.split(" x ");
            String ItemId = SplitData[0];
            int ItemNum = Integer.parseInt(SplitData[1]);

            for(int j=0;j<items.size();j++){
                if(ItemId.equals(items.get(j).getId())){
                    tempTotal += items.get(j).getPrice()*ItemNum;
                    outContent += items.get(j).getName() + " x "+ItemNum + " = "+(int)(items.get(j).getPrice()*ItemNum)+" yuan\n";
                    if(allsales.get(1).getRelatedItems().contains(ItemId)){
                        halfItems += items.get(j).getName() +"，";
                        halfTotal += items.get(j).getPrice()*ItemNum;
                        isHalf = true;
                    }
                    break;
                }
            }
        }
        outContent += "-----------------------------------\n";
        halfItems+=")，saving ";
        halfItems = halfItems.replace("，)",")");
        if(tempTotal >= 30 && isHalf){
            if((tempTotal-6)>(tempTotal-halfTotal)+halfTotal*0.5){
                outContent+="Promotion used:\n"+allsales.get(1).getDisplayName()+halfItems+(int)(tempTotal-((tempTotal-halfTotal)+halfTotal*0.5))+" yuan\n";
                outContent+="-----------------------------------\n";
                outContent+="Total："+(int)((tempTotal-halfTotal)+halfTotal*0.5) +" yuan\n";
                outContent+="===================================";
            }else{
                outContent+="Promotion used:\n"+"满30减6 yuan，saving 6 yuan\n";
                outContent+="-----------------------------------\n";
                outContent+="Total："+(int)(tempTotal-6) +" yuan\n";
                outContent+="===================================";
            }
        }else if(tempTotal >= 30 && !isHalf){
            outContent+="Promotion used:\n"+"满30减6，saving 6 yuan\n";
            outContent+="-----------------------------------\n";
            outContent+="Total："+(int)(tempTotal-6) +" yuan\n";
            outContent+="===================================";
        }else if(!(tempTotal >= 30) && isHalf){
            outContent+="Promotion used:\n"+allsales.get(1).getDisplayName()+halfItems+(int)(tempTotal-((tempTotal-halfTotal)+halfTotal*0.5));
            outContent+="-----------------------------------\n";
            outContent+="Total："+(int)((tempTotal-halfTotal)+halfTotal*0.5) +" yuan\n";
            outContent+="===================================";
        }else{
            outContent+="Total："+(int)tempTotal +" yuan\n";
            outContent+="===================================";
        }

        return outContent;
    }
}
